#!/usr/bin/env bash

unknown_conditions_icon="󱓤"

if json="$(curl --max-time 5 'wttr.in?format=j1')"; then
  current_condition="$(echo "$json" | jq '.current_condition[0]')"

  declare -A wwo_codes
  wwo_codes=(
    ["113"]="Sunny"
    ["116"]="PartlyCloudy"
    ["119"]="Cloudy"
    ["122"]="VeryCloudy"
    ["143"]="Fog"
    ["176"]="LightShowers"
    ["179"]="LightSleetShowers"
    ["182"]="LightSleet"
    ["185"]="LightSleet"
    ["200"]="ThunderyShowers"
    ["227"]="LightSnow"
    ["230"]="HeavySnow"
    ["248"]="Fog"
    ["260"]="Fog"
    ["263"]="LightShowers"
    ["266"]="LightRain"
    ["281"]="LightSleet"
    ["284"]="LightSleet"
    ["293"]="LightRain"
    ["296"]="LightRain"
    ["299"]="HeavyShowers"
    ["302"]="HeavyRain"
    ["305"]="HeavyShowers"
    ["308"]="HeavyRain"
    ["311"]="LightSleet"
    ["314"]="LightSleet"
    ["317"]="LightSleet"
    ["320"]="LightSnow"
    ["323"]="LightSnowShowers"
    ["326"]="LightSnowShowers"
    ["329"]="HeavySnow"
    ["332"]="HeavySnow"
    ["335"]="HeavySnowShowers"
    ["338"]="HeavySnow"
    ["350"]="LightSleet"
    ["353"]="LightShowers"
    ["356"]="HeavyShowers"
    ["359"]="HeavyRain"
    ["362"]="LightSleetShowers"
    ["365"]="LightSleetShowers"
    ["368"]="LightSnowShowers"
    ["371"]="HeavySnowShowers"
    ["374"]="LightSleetShowers"
    ["377"]="LightSleet"
    ["386"]="ThunderyShowers"
    ["389"]="ThunderyHeavyRain"
    ["392"]="ThunderySnowShowers"
    ["395"]="HeavySnowShowers"
  )

  declare -A weather_symbols
  weather_symbols=(
    ["Cloudy"]=""
    ["Fog"]=""
    ["HeavyRain"]=""
    ["HeavyShowers"]=""
    ["HeavySnow"]=""
    ["HeavySnowShowers"]=""
    ["LightRain"]=""
    ["LightShowers"]=""
    ["LightSleet"]=""
    ["LightSleetShowers"]=""
    ["LightSnow"]=""
    ["LightSnowShowers"]=""
    ["PartlyCloudy"]=""
    ["Sunny"]=""
    ["ThunderyHeavyRain"]=""
    ["ThunderyShowers"]=""
    ["ThunderySnowShowers"]=""
    ["VeryCloudy"]=""
  )

  weatherCode="$(echo "$current_condition" | jq -r '.weatherCode')"
  conditions_icon="${weather_symbols[${wwo_codes["$weatherCode"]}]:-"$unknown_conditions_icon"}"

  temp_F="$(echo "$current_condition" | jq -r '.temp_F')"

  windspeedMiles="$(echo "$current_condition" | jq -r '.windspeedMiles')"
else
  conditions_icon="$unknown_conditions_icon"
  temp_F="?"
  windspeedMiles="?"
fi

sketchybar --set "$NAME.conditions" icon="$conditions_icon"
sketchybar --set "$NAME.temperature" icon="" label="$temp_F"
sketchybar --set "$NAME.wind" icon="" label="$windspeedMiles"
