export EDITOR=nvim
export VISUAL=nvim
export GPG_TTY="$(tty)"

setopt autopushd

alias nf="nix flake"
alias nfl="nf lock"
alias nfu="nf update"
alias hm="home-manager"
alias hms="hm switch --show-trace"
alias nfuhms="(cd $HOME/.config/home-manager && nfu && hms)"

ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
