function {
  local insert_after="/nix/var/nix/profiles/default/bin"
  local homebrew_bin="/opt/homebrew/bin"
  local i;

  for (( i = 1; i < ${#path[@]}; i++)) do
    local entry="${path[i]}"
    if [[ "$entry" == "$insert_after" && "${path[i + 1]}" != "$homebrew_bin" ]]; then
      path[i]=("$entry" "$homebrew_bin")
      break
    fi
  done
}

: ${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CONFIG_HOME
